/***************************************************************************//**
* \file UNTITLED_tflm_y_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the UNTITLED model in float representation.
* Date: 2024-06-10 16:24:28.422734
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef UNTITLED_TFLM_Y_DATA_FLOAT_H
#define UNTITLED_TFLM_Y_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t UNTITLED_y_data_bin[];
#define UNTITLED_Y_DATA_BIN_LEN (16000)

#endif // UNTITLED_TFLM_Y_DATA_FLOAT_H

