/***************************************************************************//**
* \file UNTITLED_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains UNTITLED model data.
* Date: 2024-06-10 16:24:27.709583
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef UNTITLED_TFLM_MODEL_FLOAT_H
#define UNTITLED_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t UNTITLED_model_bin[];
#else
extern uint8_t UNTITLED_model_bin[];
#endif // CY_ML_MODEL_MEM
#define UNTITLED_MODEL_BIN_LEN (39988u)
#define UNTITLED_ARENA_SIZE (12221u)

#endif // UNTITLED_TFLM_MODEL_FLOAT_H

